### ISSUE TITLE
Using Behind Proxy

### ISSUE THREAD

**Issue by eashi** [Microsoft/vsts-cli#104]
How can it be used behind a proxy?

**Comment by tedchamb** [comment]
@eashi can you give more details on the error you are hitting?  You can run a command with the --debug argument to see more information about what is happening.

**Comment by eashi** [comment]
Thanks @tedchamb  for the reply, and apology for the too short Issue.

My client has a proxy in the network, all traffic goes through the proxy. To use Git and NPM we configure them to go through the proxy, something like this: `git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`. 

When I use vsts out of the network all is fine, when I use it on the client's network I get the error below. I am expecting that I should set some environment variable or a configuration for the cli.

I use PowerShell and on Windows 10.

Error:
 vsts code pr list --debug
Command arguments: ['code', 'pr', 'list', '--debug']
Event: Cli.PreExecute [<function VstsCLI.pre_execute at 0x0000016E74E1A950>]
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0000016E74796620>, <function OutputProducer.on_global_arguments at 0x0000016E747CF950>, <function CLIQuery.on_global_arguments at 0x0000016E747F3620>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x0000016E747966A8>]
Event: CommandLoader.OnLoadCommandTable []
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0000016E747CF9D8>, <function CLIQuery.handle_query_parameter at 0x0000016E747F36A8>]
root : Remote url: https://T-R.visualstudio.com/DefaultCollection/T%20MyProject/_git/MyProject
root : Loading cache file: C:\Users\Emad\.vsts\cli\cache\remotes.json
root : attempting to read file C:\Users\Emad\.vsts\cli\cache\remotes.json as utf-8-sig
root : Detect: Url discovery took 0:00:00.047751
root : Getting credential: vsts-cli:https://T-R.visualstudio.com
root : Getting default credential
root : Creating connection with personal access token.
root : Telemetry enabled.
root : Loading cache file: C:\Users\Emad\.vsts\python-sdk\cache\options.json
root : Loading cache file: C:\Users\Emad\.vsts\python-sdk\cache\resources.json
root : attempting to read file C:\Users\Emad\.vsts\python-sdk\cache\resources.json as utf-8-sig
root : attempting to read file C:\Users\Emad\.vsts\python-sdk\cache\options.json as utf-8-sig
root : File cache hit for resources on: https://T-R.visualstudio.com/defaultcollection
root : File cache hit for options on: https://T-R.visualstudio.com/defaultcollection
root : File cache hit for options on: https://T-R.visualstudio.com
root : Route template: _apis/{area}/{resource}
root : Route template: {project}/_apis/{area}/repositories/{repositoryId}/{resource}/{pullRequestId}
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): T-R.visualstudio.com
urllib3.connectionpool : Starting new HTTPS connection (1): T-R.visualstudio.com
urllib3.util.retry : Incremented Retry for (url='/DefaultCollection/_apis/CustomerIntelligence/Events'): Retry(total=2, connect=2, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E75764400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /DefaultCollection/_apis/CustomerIntelligence/Events
urllib3.util.retry : Incremented Retry for (url='/cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False'): Retry(total=2, connect=2, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E757644E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False
urllib3.connectionpool : Starting new HTTPS connection (2): T-R.visualstudio.com
urllib3.connectionpool : Starting new HTTPS connection (2): T-R.visualstudio.com
urllib3.util.retry : Incremented Retry for (url='/DefaultCollection/_apis/CustomerIntelligence/Events'): Retry(total=1, connect=1, read=3, redirect=None, status=None)
urllib3.util.retry : Incremented Retry for (url='/cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False'): Retry(total=1, connect=1, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A31D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /DefaultCollection/_apis/CustomerIntelligence/Events
urllib3.connectionpool : Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A35F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False
urllib3.connectionpool : Starting new HTTPS connection (3): T-R.visualstudio.com
urllib3.connectionpool : Starting new HTTPS connection (3): T-R.visualstudio.com
urllib3.util.retry : Incremented Retry for (url='/cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False'): Retry(total=0, connect=0, read=3, redirect=None, status=None)
urllib3.util.retry : Incremented Retry for (url='/DefaultCollection/_apis/CustomerIntelligence/Events'): Retry(total=0, connect=0, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A39E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /DefaultCollection/_apis/CustomerIntelligence/Events
urllib3.connectionpool : Starting new HTTPS connection (4): T-R.visualstudio.com
urllib3.connectionpool : Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A3DA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False
urllib3.connectionpool : Starting new HTTPS connection (4): T-R.visualstudio.com
msrest.exceptions : Error occurred in request., ConnectionError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /DefaultCollection/_apis/CustomerIntelligence/Events (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A3E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
root : Error occurred in request., ConnectionError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /DefaultCollection/_apis/CustomerIntelligence/Events (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A3E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A3E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /DefaultCollection/_apis/CustomerIntelligence/Events (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A3E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 194, in send
    **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /DefaultCollection/_apis/CustomerIntelligence/Events (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A3E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\common\services.py", line 236, in _send_tracking_ci_event
    ci_client.publish_events([vsts_tracking_data])
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\customer_intelligence\v4_0\customer_intelligence_client.py", line 37, in publish_events
    content=content)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 79, in _send
    response = self._send_request(request=request, headers=headers, content=content)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 54, in _send_request
    content=content, **operation_config)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 220, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 194, in send
    **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., ConnectionError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /DefaultCollection/_apis/CustomerIntelligence/Events (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758A3E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
msrest.exceptions : Error occurred in request., ConnectionError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758AF1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
root : Error occurred in request., ConnectionError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758AF1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758AF1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 668, in urlopen
    **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758AF1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 194, in send
    **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758AF1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\code\common\pull_request.py", line 108, in list_pull_requests
    skip=skip, top=top)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\git\v4_0\git_client_base.py", line 1883, in get_pull_requests
    returns_collection=True)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 79, in _send
    response = self._send_request(request=request, headers=headers, content=content)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 54, in _send_request
    content=content, **operation_config)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 220, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\msrest\service_client.py", line 194, in send
    **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., ConnectionError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758AF1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Error occurred in request., ConnectionError: HTTPSConnectionPool(host='T-R.visualstudio.com', port=443): Max retries exceeded with url: /cdbe2536-bafa-4272-8149-6a01cf10bb79/_apis/git/repositories/de02eace-a187-4bdf-bd54-4a56b959213c/pullRequests?searchCriteria.includeLinks=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016E758AF1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by tedchamb** [comment]
@eashi  Thanks for the details.  You should be able to set the HTTPS_PROXY or HTTP_PROXY environment variable to the url of your proxy.  Give it a try and let us know how it goes.

**Comment by eashi** [comment]
Thanks Ted, This works perfectly. We can close this.
