### ISSUE TITLE
Error installing vsts-cli on python 2.7.9 on Mac Sierra

### ISSUE THREAD

**Issue by eugenelim** [Microsoft/vsts-cli#136]
Installing VSTS CLI with defaults results in the following error.

Installing setuptools, pip, wheel...done.
-- Current Python executable: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
-- Installed Python executable: /Users/eu.gene.lim/lib/vsts-cli/bin/python
-- Is Python.framework
-- Installed Python executable exists
-- Created backup of installed Python executable
-- Replaced installed Python executable
-- Executing: ['/Users/eu.gene.lim/lib/vsts-cli/bin/python', '-m', 'pip', 'install', '--force-reinstall', '--cache-dir', '/var/folders/mr/jf3hm0rd59vb8mk38xp_j6lcl25rf2/T/tmpmgy7zg', 'vsts-cli', '--upgrade']
Collecting vsts-cli
  Downloading vsts_cli-0.1.0b3-py2.py3-none-any.whl
Collecting vsts-cli-code==0.1.0b3 (from vsts-cli)
  Downloading vsts_cli_code-0.1.0b3-py2.py3-none-any.whl
Collecting knack==0.2.0 (from vsts-cli)
  Downloading knack-0.2.0-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 2.2MB/s 
Collecting vsts-cli-build==0.1.0b3 (from vsts-cli)
  Downloading vsts_cli_build-0.1.0b3-py2.py3-none-any.whl
Collecting vsts-cli-work==0.1.0b3 (from vsts-cli)
  Downloading vsts_cli_work-0.1.0b3-py2.py3-none-any.whl
Collecting vsts-cli-common==0.1.0b3 (from vsts-cli)
  Downloading vsts_cli_common-0.1.0b3-py2.py3-none-any.whl
Collecting vsts-cli-team==0.1.0b3 (from vsts-cli)
  Downloading vsts_cli_team-0.1.0b3-py2.py3-none-any.whl
Collecting python-dateutil (from vsts-cli-code==0.1.0b3->vsts-cli)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 1.9MB/s 
Collecting vsts-cli-code-common==0.1.0b3 (from vsts-cli-code==0.1.0b3->vsts-cli)
  Downloading vsts_cli_code_common-0.1.0b3-py2.py3-none-any.whl
Collecting argcomplete (from knack==0.2.0->vsts-cli)
  Downloading argcomplete-1.9.3-py2.py3-none-any.whl
Collecting six (from knack==0.2.0->vsts-cli)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting pygments (from knack==0.2.0->vsts-cli)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |████████████████████████████████| 849kB 1.1MB/s 
Collecting colorama (from knack==0.2.0->vsts-cli)
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Collecting jmespath (from knack==0.2.0->vsts-cli)
  Downloading jmespath-0.9.3-py2.py3-none-any.whl
Collecting tabulate (from knack==0.2.0->vsts-cli)
  Downloading tabulate-0.8.2.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 1.8MB/s 
Collecting pyyaml (from knack==0.2.0->vsts-cli)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 1.0MB/s 
Collecting vsts-cli-build-common==0.1.0b3 (from vsts-cli-build==0.1.0b3->vsts-cli)
  Downloading vsts_cli_build_common-0.1.0b3-py2.py3-none-any.whl
Collecting vsts-cli-work-common==0.1.0b3 (from vsts-cli-work==0.1.0b3->vsts-cli)
  Downloading vsts_cli_work_common-0.1.0b3-py2.py3-none-any.whl
Collecting vsts~=0.1.0b2.dev (from vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading vsts-0.1.0b2-py2.py3-none-any.whl (580kB)
    100% |████████████████████████████████| 583kB 1.3MB/s 
Collecting keyring (from vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading keyring-11.0.0-py2.py3-none-any.whl
Collecting vsts-cli-team-common==0.1.0b3 (from vsts-cli-team==0.1.0b3->vsts-cli)
  Downloading vsts_cli_team_common-0.1.0b3-py2.py3-none-any.whl
Collecting msrest>=0.4.5 (from vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading msrest-0.4.26-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 51kB 3.5MB/s 
Collecting certifi>=2017.4.17 (from msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
    100% |████████████████████████████████| 153kB 1.7MB/s 
Collecting requests~=2.14 (from msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 2.7MB/s 
Collecting enum34>=1.0.4; python_version < "3.4" (from msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting isodate>=0.6.0 (from msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading isodate-0.6.0-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 2.3MB/s 
Collecting requests-oauthlib>=0.5.0 (from msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading requests_oauthlib-0.8.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests~=2.14->msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.3MB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests~=2.14->msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 1.8MB/s 
Collecting idna<2.7,>=2.5 (from requests~=2.14->msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 3.0MB/s 
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.5.0->msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b3->vsts-cli)
  Downloading oauthlib-2.0.6.tar.gz (127kB)
    100% |████████████████████████████████| 133kB 2.1MB/s 
Installing collected packages: argcomplete, six, pygments, colorama, jmespath, tabulate, pyyaml, knack, python-dateutil, certifi, chardet, urllib3, idna, requests, enum34, isodate, oauthlib, requests-oauthlib, msrest, vsts, keyring, vsts-cli-common, vsts-cli-code-common, vsts-cli-code, vsts-cli-build-common, vsts-cli-build, vsts-cli-work-common, vsts-cli-work, vsts-cli-team-common, vsts-cli-team, vsts-cli
  Found existing installation: argcomplete 1.9.3
    Uninstalling argcomplete-1.9.3:
      Successfully uninstalled argcomplete-1.9.3
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/mr/jf3hm0rd59vb8mk38xp_j6lcl25rf2/T/pip-t1ktxb-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
Traceback (most recent call last):
  File "/var/folders/mr/jf3hm0rd59vb8mk38xp_j6lcl25rf2/T/vsts_cli_install_tmp_XXXX.JFywNqGM", line 481, in <module>
    main()
  File "/var/folders/mr/jf3hm0rd59vb8mk38xp_j6lcl25rf2/T/vsts_cli_install_tmp_XXXX.JFywNqGM", line 441, in main
    install_cli(install_dir, tmp_dir)
  File "/var/folders/mr/jf3hm0rd59vb8mk38xp_j6lcl25rf2/T/vsts_cli_install_tmp_XXXX.JFywNqGM", line 175, in install_cli
    exec_command(cmd, cwd=os.path.dirname(cli_python))
  File "/var/folders/mr/jf3hm0rd59vb8mk38xp_j6lcl25rf2/T/vsts_cli_install_tmp_XXXX.JFywNqGM", line 131, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env, stderr=subprocess.STDOUT)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/eu.gene.lim/lib/vsts-cli/bin/python', '-m', 'pip', 'install', '--force-reinstall', '--cache-dir', '/var/folders/mr/jf3hm0rd59vb8mk38xp_j6lcl25rf2/T/tmpmgy7zg', 'vsts-cli', '--upgrade']' returned non-zero exit status 2

**Comment by atbagga** [comment]
@tedchamb Were you able to repro the original issue? 

I tried installing on a mac mini with OS Sierra and python 2.7 and I got another openssl related error which is due to "Python.org sites have stopped support for TLS versions 1.0 and 1.1.".
openssl version on the mac sierra is 0.9.8. I will try out the workarounds/fix for this.

**Kanu-Mac-mini:~ kanupriya$** **curl -L https://aka.ms/install-vsts-cli | bash**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1515  100  1515    0     0    888      0  0:00:01  0:00:01 --:--:--     0
Downloading Microsoft VSTS CLI install script from https://vstscli.blob.core.windows.net/install/install.py to /var/folders/rp/bgh4cw853952x0tfnjdhgxgc0000gn/T/vsts_cli_install_tmp_XXXX.ttDRYRKn.
######################################################################## 100.0%
/usr/bin/python

Microsoft Visual Studio Team Services CLI Install
-- Verifying Python version.
-- Python version 2.7.10 okay.

Installation directory for VSTS CLI (default: /Users/kanupriya/lib/vsts-cli): 
-- Creating directory '/Users/kanupriya/lib/vsts-cli'.

Installing. This may take a few minutes...
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz.
Traceback (most recent call last):
  File "/var/folders/rp/bgh4cw853952x0tfnjdhgxgc0000gn/T/vsts_cli_install_tmp_XXXX.ttDRYRKn", line 481, in <module>
    main()
  File "/var/folders/rp/bgh4cw853952x0tfnjdhgxgc0000gn/T/vsts_cli_install_tmp_XXXX.ttDRYRKn", line 438, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/var/folders/rp/bgh4cw853952x0tfnjdhgxgc0000gn/T/vsts_cli_install_tmp_XXXX.ttDRYRKn", line 152, in create_virtualenv
    response = urlopen(VIRTUALENV_DOWNLOAD_URL)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>

**Kanu-Mac-mini:~ kanupriya$** **openssl version -a**
OpenSSL 0.9.8zh 14 Jan 2016
built on: Nov 19 2017
platform: darwin64-x86_64-llvm
options:  bn(64,64) md2(int) rc4(ptr,char) des(idx,cisc,16,int) blowfish(idx) 
compiler: -arch x86_64 -fmessage-length=0 -pipe -Wno-trigraphs -fpascal-strings -fasm-blocks -O3 -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DMD32_REG_T=int -DOPENSSL_NO_IDEA -DOPENSSL_PIC -DOPENSSL_THREADS -DZLIB -mmacosx-version-min=10.6
OPENSSLDIR: "/System/Library/OpenSSL"

**Comment by tedchamb** [comment]
Thanks for the update @atbagga, and sorry for the delay.  I have been moved off the cli project.  The good news is that we have a whole team that is now responsible for the cli, and they can help you address this issue.  They will be actively reviewing all open issues.
