### ISSUE TITLE
Error 405 when creating a work item via CLI

### ISSUE THREAD

**Issue by jpritchett** [Microsoft/vsts-cli#166]
root : Creating connection with personal access token.
root : Telemetry enabled.
root : Cache file does not exist: C:\Users\pritcjam\.vsts\python-sdk\cache\resources.json
root : Cache file does not exist: C:\Users\pritcjam\.vsts\python-sdk\cache\options.json
root : File cache miss for resources on: http://[REMOVED].visualstudio.com
root : File cache miss for options on: http://[REMOVED].visualstudio.com
root : File cache miss for options on: http://[REMOVED].visualstudio.com
root : OPTIONS http://[REMOVED].visualstudio.com/_apis
root : OPTIONS http://[REMOVED].visualstudio.com/_apis
root : Request content: None
root : Request content: None
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTP connection (1): [REMOVED].visualstudio.com
urllib3.connectionpool : Starting new HTTP connection (1): [REMOVED].visualstudio.com
urllib3.connectionpool : http://[REMOVED].visualstudio.com:80 "OPTIONS /_apis HTTP/1.1" 405 0
urllib3.connectionpool : http://[REMOVED].visualstudio.com:80 "OPTIONS /_apis HTTP/1.1" 405 0
root : Response content: b''
root : Response content: b''
msrest.exceptions : Operation returned an invalid status code of 405.
msrest.exceptions : Operation returned an invalid status code of 405.
root : Operation returned an invalid status code of 405.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\common\services.py", line 237, in _send_tracking_ci_event
    ci_client.publish_events([vsts_tracking_data])
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\customer_intelligence\v4_0\customer_intelligence_client.py", line 37, in publish_events
    content=content)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 68, in _send
    query_parameters=query_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 105, in _create_request_message
    location = self._get_resource_location(location_id)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 137, in _get_resource_location
    VssClient._locations_cache[self.config.base_url] = self._get_resource_locations(all_host_types=False)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 173, in _get_resource_locations
    response = self._send_request(request, headers=headers)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 59, in _send_request
    self._handle_error(request, response)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 260, in _handle_error
    status_code=response.status_code))
vsts.exceptions.VstsClientRequestError: Operation returned an invalid status code of 405.
root : Operation returned an invalid status code of 405.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\work\common\work_item.py", line 95, in create_work_item
    client = get_work_item_tracking_client(team_instance)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\common\services.py", line 109, in get_work_item_tracking_client
    return connection.get_client('vsts.work_item_tracking.v4_0.work_item_tracking_client.WorkItemTrackingClient')
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_connection.py", line 35, in get_client
    self._client_cache[client_type] = self._get_client_instance(client_class)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_connection.py", line 48, in _get_client_instance

**Comment by tedchamb** [comment]
@jpritchett When targeting the online service you need to use an HTTPS URL.

Your URL:  http://[REMOVED].visualstudio.com:80
Correct URL: https://[REMOVED].visualstudio.com

Can you make this change and try again?

**Comment by jpritchett** [comment]
thanks , did that now got this
Failed to authenticate using the supplied token.
so suspecting corporate network is blocking something. Will investigate further my end.

**Comment by tedchamb** [comment]
@jpritchett You may find information at the following page helpful.   It sounds like you have an invalid personal access token stored in keyring.  Specifying the `--instance` argument will allow you to set different PATs for different vsts accounts or TFS servers.  If you don't supply that argument it will set a fallback PAT to use for all instances that haven't been explicitly set.

https://aka.ms/vsts-cli-auth
