### ISSUE TITLE
Unicode characters in exceptions cause logging exceptions

### ISSUE THREAD

**Issue by zarenner** [Microsoft/vsts-cli#192]
A UnicodeEncodeError is raised when the exception text includes a Unicode character.

Windows, Python 3.6.5:
> (env) c:\repos\vsts-cli>vsts admin banner add -m "test"
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\__init__.py", line 994, in emit
    stream.write(msg)
  File "C:\Program Files\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0332' in position 81: character maps to <undefined>
Call stack:
  File "c:\repos\vsts-cli\env\Scripts\vsts-script.py", line 11, in <module>
    load_entry_point('vsts-cli', 'console_scripts', 'vsts')()
  File "c:\repos\vsts-cli\src\vsts-cli\vsts\cli\__main__.py", line 13, in main
    exit_code = vsts_cli.invoke(sys.argv[1:])
  File "c:\repos\vsts-cli\src\vsts-cli\vsts\cli\vsts_cli.py", line 38, in invoke
    return CLI.invoke(self, args, initial_invocation_data, out_file)
  File "c:\repos\vsts-cli\env\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\repos\vsts-cli\env\lib\site-packages\knack\invocation.py", line 172, in execute
    cmd_result = parsed_args.func(params)
  File "c:\repos\vsts-cli\env\lib\site-packages\knack\commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "c:\repos\vsts-cli\env\lib\site-packages\knack\commands.py", line 203, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\repos\vsts-cli\src\common_modules\vsts-cli-admin-common\vsts\cli\admin\common\banner.py", line 78, in banner_add
    setting_add_or_update(entries=entries, user_scope=USER_SCOPE_HOST, team_instance=team_instance, detect=detect)
  File "c:\repos\vsts-cli\src\common_modules\vsts-cli-admin-common\vsts\cli\admin\common\setting.py", line 20, in setting_add_or_update
    client.set_entries(entries=entries, user_scope=user_scope)
  File "c:\repos\vsts-cli\env\lib\site-packages\vsts\settings\v4_0\settings_client.py", line 75, in set_entries
    content=content)
  File "c:\repos\vsts-cli\env\lib\site-packages\vsts\vss_client.py", line 90, in _send
    response = self._send_request(request=request, headers=headers, content=content)
  File "c:\repos\vsts-cli\env\lib\site-packages\vsts\vss_client.py", line 59, in _send_request
    self._handle_error(request, response)
  File "c:\repos\vsts-cli\env\lib\site-packages\vsts\vss_client.py", line 235, in _handle_error
    raise VstsServiceError(wrapped_exception)
  File "c:\repos\vsts-cli\env\lib\site-packages\vsts\exceptions.py", line 35, in __init__
    inner_exception=self.inner_exception)
  File "c:\repos\vsts-cli\env\lib\site-packages\msrest\exceptions.py", line 66, in __init__
    _LOGGER.debug(message)
Message: 'Access Denied: Zach̲ Re̲nner needs the following permission(s) on the resource Global to perform this action: Write setting entries'

**Comment by gauravsaralMs** [comment]
Not able to repro with latest setup..
Changed my name to "GaurÄv Saral e̲" and tried..

@zarenner : Can you please confirm if the issue is still there with latest bits?

cc: @tedchamb  @snankani

**Comment by zarenner** [comment]
Not able to repro either with latest release. Not sure what PR would have fixed this, but closing for now.
