### ISSUE TITLE
Install on macOS with Python3 fails

### ISSUE THREAD

**Issue by carlowahlstedt** [Microsoft/vsts-cli#77]
Using these [install instructions](https://docs.microsoft.com/en-us/cli/vsts/install?view=vsts-cli-latest) and just accepting defaults:

```
-- The executable will be in '/Users/carlo.wahlstedt/bin'.
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz.
-- Downloaded virtualenv package to /var/folders/zd/kbyf92z92517trsjwh5h3mg9xp9gss/T/tmpskokwh3b/virtualenv-15.0.0.tar.gz.
-- Checksum of /var/folders/zd/kbyf92z92517trsjwh5h3mg9xp9gss/T/tmpskokwh3b/virtualenv-15.0.0.tar.gz OK.
-- Extracting '/var/folders/zd/kbyf92z92517trsjwh5h3mg9xp9gss/T/tmpskokwh3b/virtualenv-15.0.0.tar.gz' to '/var/folders/zd/kbyf92z92517trsjwh5h3mg9xp9gss/T/tmpskokwh3b'.
-- Executing: ['/usr/local/opt/python3/bin/python3.6', 'virtualenv.py', '--python', '/usr/local/opt/python3/bin/python3.6', '/Users/carlo.wahlstedt/lib/vsts-cli']
Already using interpreter /usr/local/opt/python3/bin/python3.6
Using base prefix '/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/carlo.wahlstedt/lib/vsts-cli/bin/python3.6
Also creating executable in /Users/carlo.wahlstedt/lib/vsts-cli/bin/python
Installing setuptools, pip, wheel...done.
-- Current executable /usr/local/opt/python3/bin/python3.6
-- Installed executable /Users/carlo.wahlstedt/lib/vsts-cli/bin/python
-- Is Python.framework
-- Installed Python executable exists
-- Created backup of installed Python executable
-- Replaced installed Python executable
-- Executing: ['/Users/carlo.wahlstedt/lib/vsts-cli/bin/pip', 'install', '--cache-dir', '/var/folders/zd/kbyf92z92517trsjwh5h3mg9xp9gss/T/tmpskokwh3b', '--pre', 'vsts-cli', '--upgrade', '--extra-index-url', 'https://vstscli.azurewebsites.net/']
Requirement already up-to-date: vsts-cli in /usr/local/lib/python3.6/site-packages
Requirement already up-to-date: knack in /usr/local/lib/python3.6/site-packages (from vsts-cli)
Requirement already up-to-date: vsts-cli-common==0.1.0b2.dev4422419 in /usr/local/lib/python3.6/site-packages (from vsts-cli)
Requirement already up-to-date: vsts-cli-work==0.1.0b2.dev4422419 in /usr/local/lib/python3.6/site-packages (from vsts-cli)
Requirement already up-to-date: vsts-cli-build==0.1.0b2.dev4422419 in /usr/local/lib/python3.6/site-packages (from vsts-cli)
Requirement already up-to-date: vsts-cli-code==0.1.0b2.dev4422419 in /usr/local/lib/python3.6/site-packages (from vsts-cli)
Requirement already up-to-date: vsts-cli-team==0.1.0b2.dev4422419 in /usr/local/lib/python3.6/site-packages (from vsts-cli)
Requirement already up-to-date: jmespath in /usr/local/lib/python3.6/site-packages (from knack->vsts-cli)
Requirement already up-to-date: tabulate in /usr/local/lib/python3.6/site-packages (from knack->vsts-cli)
Requirement already up-to-date: pygments in /usr/local/lib/python3.6/site-packages (from knack->vsts-cli)
Requirement already up-to-date: pyyaml in /usr/local/lib/python3.6/site-packages (from knack->vsts-cli)
Requirement already up-to-date: argcomplete in /usr/local/lib/python3.6/site-packages (from knack->vsts-cli)
Requirement already up-to-date: colorama in /usr/local/lib/python3.6/site-packages (from knack->vsts-cli)
Requirement already up-to-date: six in /usr/local/lib/python3.6/site-packages (from knack->vsts-cli)
Requirement already up-to-date: vsts~=0.1.0b2.dev in /usr/local/lib/python3.6/site-packages (from vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: keyring in /usr/local/lib/python3.6/site-packages (from vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.6/site-packages (from vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: vsts-cli-work-common==0.1.0b2.dev4422419 in /usr/local/lib/python3.6/site-packages (from vsts-cli-work==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: vsts-cli-build-common==0.1.0b2.dev4422419 in /usr/local/lib/python3.6/site-packages (from vsts-cli-build==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: vsts-cli-code-common==0.1.0b2.dev4422419 in /usr/local/lib/python3.6/site-packages (from vsts-cli-code==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: vsts-cli-team-common==0.1.0b2.dev4422419 in /usr/local/lib/python3.6/site-packages (from vsts-cli-team==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: msrest>=0.4.5 in /usr/local/lib/python3.6/site-packages (from vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: requests-oauthlib>=0.5.0 in /usr/local/lib/python3.6/site-packages (from msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: requests~=2.14 in /usr/local/lib/python3.6/site-packages (from msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: isodate>=0.5.4 in /usr/local/lib/python3.6/site-packages (from msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: oauthlib>=0.6.2 in /usr/local/lib/python3.6/site-packages (from requests-oauthlib>=0.5.0->msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests~=2.14->msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests~=2.14->msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests~=2.14->msrest>=0.4.5->vsts~=0.1.0b2.dev->vsts-cli-common==0.1.0b2.dev4422419->vsts-cli)
Traceback (most recent call last):
  File "/var/folders/zd/kbyf92z92517trsjwh5h3mg9xp9gss/T/vsts_cli_install_tmp_XXXX.uskjUUOL", line 444, in <module>
    main()
  File "/var/folders/zd/kbyf92z92517trsjwh5h3mg9xp9gss/T/vsts_cli_install_tmp_XXXX.uskjUUOL", line 426, in main
    exec_filepath = create_executable(exec_dir, install_dir)
  File "/var/folders/zd/kbyf92z92517trsjwh5h3mg9xp9gss/T/vsts_cli_install_tmp_XXXX.uskjUUOL", line 173, in create_executable
    cur_stat = os.stat(exec_filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/carlo.wahlstedt/bin/vsts'
```

macOS: 10.12.6

**Comment by willsmythe** [comment]
@carlowahlstedt - we identified the problem. It appears to be Python 3 specific. We patched the install script. 

Try running the install again: `curl -L https://aka.ms/install-vsts-cli | bash`.

This will attempt to use Python 2 (if you have it installed). It should also not fail on the step it previously failed on.

Btw, even though the original install says it failed, you likely have a `vsts` script under `/usr/local/bin` (which should be in your $PATH) that you can run to launch the VSTS CLI.

**Comment by carlowahlstedt** [comment]
Installation successful! Good work!

I didn't actually try the `vsts` command prior to doing the install. Jumped the gun and started the install again before reading the entire post, but it worked. So I think we're in good shape now.

Thanks!

**Comment by willsmythe** [comment]
@carlowahlstedt - thanks for verifying, and glad it's working for you.

I am going to keep this issue open since we still have a problem with Python3 on Mac. The updated install script favors Python2, which allowed the VSTS CLI to install successfully.

**Comment by carlowahlstedt** [comment]
👍🏼

Let me know how/if I can assist.

**Comment by atbagga** [comment]
I could not repro this issue now. Tried to run the install script with python 3. 
Since the original issue was fixed and this was only to fix the script. 
Marking it closed.
